# Generated by Django 6.0.4 on 2026-04-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_contact_links_to_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='hero_image_upload',
            field=models.ImageField(blank=True, help_text='Upload a project screenshot or hero image. Overrides the legacy path above.', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='featuredproject',
            name='hero_image',
            field=models.CharField(blank=True, help_text='Path relative to static/, for example img/work1.png (legacy — prefer uploading below).', max_length=255),
        ),
    ]
