# Generated by Django 6.0.4 on 2026-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_featuredproject_hero_image_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='live_url',
            field=models.URLField(blank=True, help_text='Optional live URL of the website, e.g. https://example.com'),
        ),
    ]
