# Generated by Django 6.0.4 on 2026-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsectionsettings',
            name='heading',
            field=models.CharField(default='Karibu My Shop', max_length=200),
        ),
    ]
