# Generated by Django 6.0.4 on 2026-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_shopitem_image_upload_and_image_path_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("visit_count", models.PositiveBigIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField()),
                ("last_path", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
