# Generated by Django 6.0.4 on 2026-07-12 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(
                        help_text="Upload your current CV as a PDF.",
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("cv_label", models.CharField(default="View CV", max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portfolio Settings",
                "verbose_name_plural": "Portfolio Settings",
            },
        ),
    ]
