# Generated by Django 6.0.4 on 2026-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_portfoliosettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_eyebrow", models.CharField(default="Hello, I'm", max_length=80)),
                (
                    "hero_description",
                    models.CharField(
                        default="Let's design and build digital experiences that convert, engage, and stand out.",
                        max_length=240,
                    ),
                ),
                (
                    "hero_cta_label",
                    models.CharField(default="View My Work", max_length=60),
                ),
                (
                    "services_eyebrow",
                    models.CharField(default="My Expertise", max_length=80),
                ),
                (
                    "services_heading",
                    models.CharField(default="Services", max_length=100),
                ),
                (
                    "services_heading_highlight",
                    models.CharField(default="& Solutions", max_length=100),
                ),
                (
                    "services_intro",
                    models.CharField(
                        default="Select a service to see what the engagement includes, how I approach it, and what you can expect.",
                        max_length=240,
                    ),
                ),
                (
                    "work_eyebrow",
                    models.CharField(default="Selected Projects", max_length=80),
                ),
                ("work_heading", models.CharField(default="Featured", max_length=100)),
                (
                    "work_heading_highlight",
                    models.CharField(default="Works", max_length=100),
                ),
                (
                    "contact_eyebrow",
                    models.CharField(default="Get in touch", max_length=80),
                ),
                ("contact_heading", models.CharField(default="Let's", max_length=100)),
                (
                    "contact_heading_highlight",
                    models.CharField(default="Collaborate", max_length=100),
                ),
                (
                    "contact_intro",
                    models.TextField(
                        default="Have a project in mind? Looking for a partner to build something impactful? Message me on WhatsApp and let's start the conversation where it is fastest."
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        default="MUKO. Built with Passion.", max_length=160
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Content Settings",
                "verbose_name_plural": "Site Content Settings",
            },
        ),
    ]
