# Generated by Django 6.0.4 on 2026-07-12 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_sitecontentsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredproject",
            name="hero_image_upload",
            field=models.FileField(
                blank=True,
                help_text="Upload a project screenshot or hero image. Overrides the legacy path above. Supports WebP, PNG, JPG.",
                null=True,
                upload_to="projects/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.FileField(
                upload_to="projects/gallery/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shopitem",
            name="image_upload",
            field=models.FileField(
                blank=True,
                help_text="Upload a shop image. This is used first when present. Supports WebP, PNG, JPG.",
                null=True,
                upload_to="shop/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp", "gif"]
                    )
                ],
            ),
        ),
    ]
