# Generated by Django 5.0.14 on 2026-07-13 19:13

import django.db.models.deletion
from django.db import migrations, models


def seed_default_services(apps, schema_editor):
    SiteContentSettings = apps.get_model('core', 'SiteContentSettings')
    Service = apps.get_model('core', 'Service')

    # Get or create the site content settings singleton
    site_content = SiteContentSettings.objects.first()
    if not site_content:
        site_content = SiteContentSettings.objects.create()

    # Create the default services
    services_data = [
        {
            'title': 'Web Development',
            'slug': 'web',
            'icon': 'code-2',
            'short_description': 'Fast, scalable applications built around real business goals.',
            'description': 'A complete path from a validated idea to a secure, maintainable web product—not just a collection of pages.',
            'includes': 'Discovery and technical planning\nResponsive frontend implementation\nDjango, APIs and database architecture\nAuthentication, admin and integrations',
            'outcomes': 'A production-ready application\nClean, maintainable source code\nDeployment and handover documentation\nA foundation that can scale',
            'tags': '',
            'column_span': 2,
            'show_bg_icon': True,
            'display_order': 10,
        },
        {
            'title': 'UI/UX Design',
            'slug': 'design',
            'icon': 'pen-tool',
            'short_description': 'Clear, intuitive interfaces designed around how people behave.',
            'description': 'Interfaces shaped around user needs, business priorities and a visual system that stays coherent as the product grows.',
            'includes': 'User flows and information architecture\nWireframes and interactive prototypes\nHigh-fidelity responsive UI\nReusable design system foundations',
            'outcomes': 'Clearer customer journeys\nFaster development decisions\nConsistent visual language\nDesigns ready for implementation',
            'tags': '',
            'column_span': 2,
            'show_bg_icon': False,
            'display_order': 20,
        },
        {
            'title': 'Digital Platforms',
            'slug': 'platforms',
            'icon': 'layout-grid',
            'short_description': 'Connected digital systems that help organizations operate and grow.',
            'description': 'End-to-end platforms that connect content, operations and customer experiences into one dependable system.',
            'includes': 'Requirements and workflow mapping\nCMS, portal or marketplace architecture\nThird-party API integrations\nRoles, permissions and reporting',
            'outcomes': 'Less manual operational work\nOne reliable source of truth\nBetter customer self-service\nA platform built for expansion',
            'tags': '',
            'column_span': 2,
            'show_bg_icon': False,
            'display_order': 30,
        },
        {
            'title': 'Cloud Infrastructure',
            'slug': 'cloud',
            'icon': 'cloud',
            'short_description': 'Secure, observable environments built to deploy reliably and scale safely.',
            'description': 'Practical cloud foundations that keep applications deployable, observable and resilient without unnecessary complexity.',
            'includes': 'Environment and deployment architecture\nCI/CD pipeline configuration\nSecurity, backups and access controls\nMonitoring and performance baselines',
            'outcomes': 'Repeatable deployments\nReduced downtime risk\nClear operational visibility\nInfrastructure ready to scale',
            'tags': 'AWS, Azure',
            'column_span': 3,
            'show_bg_icon': False,
            'display_order': 40,
        },
        {
            'title': 'Performance & SEO',
            'slug': 'seo',
            'icon': 'search',
            'short_description': 'Technical improvements that make your site faster, easier to find, and easier to use.',
            'description': 'Technical and content-focused improvements that help real people—and search engines—reach and use your site effectively.',
            'includes': 'Core Web Vitals and speed audit\nTechnical SEO and crawl review\nMetadata and structured content\nAccessibility and conversion checks',
            'outcomes': 'Faster page experiences\nImproved search visibility\nLower user drop-off\nA prioritized optimization roadmap',
            'tags': '',
            'column_span': 3,
            'show_bg_icon': False,
            'display_order': 50,
        },
    ]

    for data in services_data:
        Service.objects.get_or_create(
            site_content=site_content,
            slug=data['slug'],
            defaults=data
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_featuredproject_hero_image_upload_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for frontend script logic, e.g., 'web', 'design', 'platforms', 'cloud', 'seo'"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name, e.g., 'code-2', 'pen-tool', 'layout-grid', 'cloud', 'search'",
                        max_length=50,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief description displayed on the main card."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description displayed in the modal."
                    ),
                ),
                (
                    "includes",
                    models.TextField(
                        help_text="What the service includes. One item per line."
                    ),
                ),
                (
                    "outcomes",
                    models.TextField(
                        help_text="Typical outcomes of the service. One item per line."
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Optional tags, comma-separated. E.g., 'AWS, Azure' for cloud infrastructure.",
                        max_length=255,
                    ),
                ),
                (
                    "column_span",
                    models.PositiveIntegerField(
                        choices=[(2, "2 Columns"), (3, "3 Columns"), (6, "Full Width")],
                        default=2,
                        help_text="Card width in the grid (total grid is 6 columns).",
                    ),
                ),
                (
                    "show_bg_icon",
                    models.BooleanField(
                        default=False,
                        help_text="Show a large semi-transparent icon in the card background.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "site_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.sitecontentsettings",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.RunPython(seed_default_services),
    ]

