# Generated by Django 5.0.14 on 2026-07-13 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="device_type",
            field=models.CharField(
                default="Desktop",
                help_text="Mobile, Tablet, Desktop, or Bot/Crawler.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="is_bot",
            field=models.BooleanField(
                default=False,
                help_text="True if this visitor is identified as a search crawler or bot.",
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="region",
            field=models.CharField(
                default="Unknown",
                help_text="Detected region or country.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("path", models.CharField(max_length=255)),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.visitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "is_bot"],
                        name="core_visitl_timesta_fdb627_idx",
                    )
                ],
            },
        ),
    ]
