# Generated by Django 6.0.8 on 2026-09-06

import django.core.validators
from django.db import migrations, models


IMAGE_UPLOAD_EXTENSIONS = ['png', 'jpg', 'jpeg', 'jfif', 'webp', 'avif', 'gif']


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shopcategory_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproject',
            name='hero_image_upload',
            field=models.FileField(
                blank=True,
                help_text='Upload a project screenshot or hero image. Overrides the legacy path above. Supports PNG, JPG/JFIF, WebP, AVIF, and GIF.',
                null=True,
                upload_to='projects/',
                validators=[django.core.validators.FileExtensionValidator(IMAGE_UPLOAD_EXTENSIONS)],
            ),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(
                upload_to='projects/gallery/',
                validators=[django.core.validators.FileExtensionValidator(IMAGE_UPLOAD_EXTENSIONS)],
            ),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='image_upload',
            field=models.FileField(
                blank=True,
                help_text='Optional category image. Supports PNG, JPG/JFIF, WebP, AVIF, and GIF.',
                null=True,
                upload_to='shop/categories/',
                validators=[django.core.validators.FileExtensionValidator(IMAGE_UPLOAD_EXTENSIONS)],
            ),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image_upload',
            field=models.FileField(
                blank=True,
                help_text='Upload a shop image. This is used first when present. Supports PNG, JPG/JFIF, WebP, AVIF, and GIF.',
                null=True,
                upload_to='shop/',
                validators=[django.core.validators.FileExtensionValidator(IMAGE_UPLOAD_EXTENSIONS)],
            ),
        ),
    ]
