"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

_SAFE_SUBCOMMANDS = {'test', 'check'}
_is_safe_subcommand = bool(sys.argv[1:2] and sys.argv[1] in _SAFE_SUBCOMMANDS)


def load_dotenv(dotenv_path):
    if not dotenv_path.exists():
        return

    for raw_line in dotenv_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def get_bool_env(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 't', 'yes', 'on'}


def get_list_env(name, default=None):
    value = os.getenv(name)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


def get_int_env(name, default=0):
    value = os.getenv(name)
    if value is None:
        return default
    return int(value)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').strip().lower()
IS_PRODUCTION = DJANGO_ENV == 'production'
WHATSAPP_CONTACT_URL = os.getenv(
    'WHATSAPP_CONTACT_URL',
    'https://wa.me/254717157165?text=Hi%20Muko%2C%20I%27d%20like%20to%20talk%20about%20a%20project.',
)
WHATSAPP_PHONE_DISPLAY = os.getenv('WHATSAPP_PHONE_DISPLAY', '0717 157 165')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEFAULT_SECRET_KEY = 'django-insecure-68s8c_z0d$$_o-(n%+^)wir90te4%f^ooa)c&e!z3n04!50buu'
SECRET_KEY = os.getenv('SECRET_KEY', DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DEBUG', not IS_PRODUCTION)

if IS_PRODUCTION and SECRET_KEY == DEFAULT_SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY must be set from the environment in production.')

ALLOWED_HOSTS = get_list_env(
    'ALLOWED_HOSTS',
    ['127.0.0.1', 'localhost'] if (DEBUG or _is_safe_subcommand) else [],
)

if not DEBUG and not ALLOWED_HOSTS and not _is_safe_subcommand:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be configured when DEBUG is disabled.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.VisitorTrackingMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.contact_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    import re
    match = re.match(
        r'(?P<engine>\w+)://(?:(?P<user>[^:]+)(?::(?P<pass>[^@]+))?@)?(?P<host>[^:/]+)(?::(?P<port>\d+))?/(?P<name>.+)',
        DATABASE_URL,
    )
    if match:
        engine_map = {
            'postgresql': 'django.db.backends.postgresql',
            'postgres': 'django.db.backends.postgresql',
            'mysql': 'django.db.backends.mysql',
        }
        DATABASES = {
            'default': {
                'ENGINE': engine_map.get(match.group('engine'), 'django.db.backends.postgresql'),
                'NAME': match.group('name'),
                'USER': match.group('user') or '',
                'PASSWORD': match.group('pass') or '',
                'HOST': match.group('host'),
                'PORT': match.group('port') or '',
            }
        }
    else:
        raise ImproperlyConfigured(f'Invalid DATABASE_URL format: {DATABASE_URL}')
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

CSRF_TRUSTED_ORIGINS = get_list_env('CSRF_TRUSTED_ORIGINS', [])

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = get_bool_env('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = get_bool_env('CSRF_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_HTTPONLY = get_bool_env('CSRF_COOKIE_HTTPONLY', False)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'same-origin')
SECURE_SSL_REDIRECT = get_bool_env('SECURE_SSL_REDIRECT', IS_PRODUCTION)
SECURE_HSTS_SECONDS = get_int_env('SECURE_HSTS_SECONDS', 3600 if IS_PRODUCTION else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS',
    IS_PRODUCTION and SECURE_HSTS_SECONDS > 0,
)
SECURE_HSTS_PRELOAD = get_bool_env(
    'SECURE_HSTS_PRELOAD',
    IS_PRODUCTION and SECURE_HSTS_SECONDS > 0,
)

if get_bool_env('USE_X_FORWARDED_PROTO', IS_PRODUCTION):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.locmem.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = get_int_env('EMAIL_PORT', 25)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = get_bool_env('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = get_bool_env('EMAIL_USE_SSL', False)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@muko.local')
CONTACT_NOTIFICATION_EMAIL = os.getenv('CONTACT_NOTIFICATION_EMAIL', 'deltonmukoyakuya@gmail.com')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

VISITOR_TRACKING_COOLDOWN_SECONDS = get_int_env('VISITOR_TRACKING_COOLDOWN_SECONDS', 1800)
TRUST_X_FORWARDED_FOR = get_bool_env('TRUST_X_FORWARDED_FOR', False)
